import * as THREE from './vendor/three.module.js';
export function createTerrain({onPin,onSceneReady}){
 const canvas=document.querySelector('#terrain');const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setSize(innerWidth,innerHeight);renderer.setClearColor(0xacc9b0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
 const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x9ab89b,.0011);const camera=new THREE.PerspectiveCamera(44,innerWidth/innerHeight,1,3000);
 scene.add(new THREE.HemisphereLight(0xddeacf,0x153923,1.35));const sun=new THREE.DirectionalLight(0xffe8b4,2.3);sun.position.set(-200,400,200);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-600;sun.shadow.camera.right=600;sun.shadow.camera.top=600;sun.shadow.camera.bottom=-600;sun.shadow.camera.far=1500;sun.shadow.normalBias=2;scene.add(sun);
 let seed=821;function rand(){seed=(seed*16807)%2147483647;return(seed-1)/2147483646}function hash(x,z){return Math.sin(x*127.1+z*311.7)*43758.5453123%1}function noise(x,z){const ix=Math.floor(x),iz=Math.floor(z),fx=x-ix,fz=z-iz;const u=fx*fx*(3-2*fx),v=fz*fz*(3-2*fz);const h=(a,b)=>Math.abs(hash(a,b));return THREE.MathUtils.lerp(THREE.MathUtils.lerp(h(ix,iz),h(ix+1,iz),u),THREE.MathUtils.lerp(h(ix,iz+1),h(ix+1,iz+1),u),v)}
 function height(x,z){const ridges=60*Math.sin(x*.006+z*.004)+26*Math.cos(z*.013)+20*Math.sin(x*.016-z*.011);let v=0,amp=35,f=.008;for(let i=0;i<5;i++){v+=noise(x*f+5,z*f+17)*amp;f*=2.05;amp*=.5}const valley=Math.exp(-Math.pow((x-100*Math.sin(z*.007)-100)/90,2))*50;return Math.max(-5,35+ridges+v-valley)}
 const geo=new THREE.PlaneGeometry(2200,2200,260,260);geo.rotateX(-Math.PI/2);const pos=geo.attributes.position;const colors=[];let color=new THREE.Color();for(let i=0;i<pos.count;i++){const x=pos.getX(i),z=pos.getZ(i),y=height(x,z);pos.setY(i,y);const blend=noise(x*.035,z*.035);color.setHSL(.25+blend*.035,.30+blend*.18,.17+blend*.13+(y/220)*.04);colors.push(color.r,color.g,color.b)}geo.setAttribute('color',new THREE.Float32BufferAttribute(colors,3));geo.computeVertexNormals();const ground=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({vertexColors:true,roughness:1}));scene.add(ground);
 const leafCanvas=document.createElement('canvas');leafCanvas.width=128;leafCanvas.height=128;const lc=leafCanvas.getContext('2d');lc.fillStyle='#718561';lc.fillRect(0,0,128,128);for(let i=0;i<2800;i++){const b=Math.floor(80+rand()*140);lc.fillStyle=`rgb(${b},${b},${b})`;lc.fillRect(rand()*128,rand()*128,1+rand()*3,1+rand()*3)}const leafTexture=new THREE.CanvasTexture(leafCanvas);leafTexture.wrapS=leafTexture.wrapT=THREE.RepeatWrapping;
 ground.receiveShadow=true;ground.material.bumpMap=leafTexture;ground.material.bumpScale=.7;const trees=new THREE.InstancedMesh(new THREE.SphereGeometry(1,7,5),new THREE.MeshStandardMaterial({color:0xffffff,roughness:1,bumpMap:leafTexture,bumpScale:.65}),68000);const dummy=new THREE.Object3D();for(let i=0;i<68000;i++){const x=(rand()-.5)*1900,z=(rand()-.5)*1900,y=height(x,z),s=2+rand()*3;const tea=x>-175&&x<195&&z>130&&z<305;dummy.position.set(x,y+s*.7,z);dummy.scale.set(tea?.05:s,s*(1+rand()*.65),tea?.05:s);dummy.rotation.set(rand()*.3,rand()*6,rand()*.3);dummy.updateMatrix();trees.setMatrixAt(i,dummy.matrix);color.setHSL(.24+rand()*.065,.30+rand()*.25,.07+rand()*.095);trees.setColorAt(i,color)}trees.castShadow=true;trees.receiveShadow=true;scene.add(trees);
 // Contour-following tea rows are real 3D ribbons across the foreground hills.
 for(let r=0;r<30;r++){const p=[];for(let s=0;s<90;s++){const x=-170+s*4,z=140+r*5+12*Math.sin(x*.014);p.push(new THREE.Vector3(x,height(x,z)+1.6,z))}const curve=new THREE.CatmullRomCurve3(p);const mesh=new THREE.Mesh(new THREE.TubeGeometry(curve,90,1.3,4,false),new THREE.MeshStandardMaterial({color:r%3===0?0x8aab45:0x648d3b,roughness:1}));scene.add(mesh)}
 const water=new THREE.Mesh(new THREE.PlaneGeometry(2600,2600),new THREE.MeshStandardMaterial({color:0x578a83,metalness:.3,roughness:.26,transparent:true,opacity:.9}));water.rotation.x=-Math.PI/2;water.position.y=-2;scene.add(water);
 const riverVertices=[],riverIndices=[];for(let i=0;i<300;i++){const z=-850+i*6,x=100*Math.sin(z*.007)+100;for(const dx of [-2,2])riverVertices.push(x+dx,height(x+dx,z)+.35,z);if(i<299){let a=i*2;riverIndices.push(a,a+1,a+2,a+1,a+3,a+2)}}const riverGeo=new THREE.BufferGeometry();riverGeo.setAttribute('position',new THREE.Float32BufferAttribute(riverVertices,3));riverGeo.setIndex(riverIndices);riverGeo.computeVertexNormals();const river=new THREE.Mesh(riverGeo,new THREE.MeshStandardMaterial({color:0x729d8f,metalness:.4,roughness:.25,side:THREE.DoubleSide}));scene.add(river);
 const cloudCanvas=document.createElement('canvas');cloudCanvas.width=128;cloudCanvas.height=128;const ctx=cloudCanvas.getContext('2d'),g=ctx.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,'rgba(239,249,224,.4)');g.addColorStop(.5,'rgba(239,249,224,.12)');g.addColorStop(1,'rgba(239,249,224,0)');ctx.fillStyle=g;ctx.fillRect(0,0,128,128);const tex=new THREE.CanvasTexture(cloudCanvas);const clouds=[];for(let i=0;i<22;i++){const s=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,depthWrite:false,opacity:.45}));s.position.set((rand()-.5)*1900,110+rand()*90,(rand()-.5)*1900);s.scale.set(230+rand()*250,40+rand()*80,1);clouds.push(s);scene.add(s)}
 // Palm-lined waterways form a second continuous landscape beyond the highlands.
 const lagoon=new THREE.Mesh(new THREE.PlaneGeometry(2400,2400,60,60),new THREE.MeshStandardMaterial({color:0x376e69,metalness:.6,roughness:.28}));lagoon.rotation.x=-Math.PI/2;lagoon.position.set(0,-1,-2400);scene.add(lagoon);
 const palms=[];for(let island=0;island<17;island++){const cx=(island%4)*220-350,cz=-1800-Math.floor(island/4)*230,rx=70+rand()*55,rz=70+rand()*80;const sand=new THREE.Mesh(new THREE.SphereGeometry(1,32,12),new THREE.MeshStandardMaterial({color:0xd2c79a,roughness:1}));sand.position.set(cx,-1,cz);sand.scale.set(rx+5,5,rz+5);scene.add(sand);const land=new THREE.Mesh(new THREE.SphereGeometry(1,32,12),new THREE.MeshStandardMaterial({color:0x48773e,roughness:1}));land.position.set(cx,0,cz);land.scale.set(rx,5,rz);scene.add(land);for(let n=0;n<14;n++){const angle=rand()*Math.PI*2,rad=.3+rand()*.55;palms.push({x:cx+Math.cos(angle)*rx*rad,z:cz+Math.sin(angle)*rz*rad,h:12+rand()*10})}}
 const trunks=new THREE.InstancedMesh(new THREE.CylinderGeometry(.7,1.1,1,6),new THREE.MeshStandardMaterial({color:0x8c8862,roughness:1}),palms.length);const leafGeo=new THREE.BufferGeometry();const lv=[],li=[];for(let i=0;i<10;i++){const t=i/9,y=5*Math.sin(t*Math.PI*.8)-t*4;const w=Math.sin(t*Math.PI)*1.6;lv.push(t*13,y,-w,t*13,y,w);if(i<9){const a=i*2;li.push(a,a+1,a+2,a+1,a+3,a+2)}}leafGeo.setAttribute('position',new THREE.Float32BufferAttribute(lv,3));leafGeo.setIndex(li);leafGeo.computeVertexNormals();const palmLeaves=new THREE.InstancedMesh(leafGeo,new THREE.MeshStandardMaterial({color:0x34692f,side:THREE.DoubleSide,roughness:1}),palms.length*7);palms.forEach((p,i)=>{dummy.position.set(p.x,p.h/2+3,p.z);dummy.rotation.set(.07,rand()*6,.08);dummy.scale.set(1,p.h,1);dummy.updateMatrix();trunks.setMatrixAt(i,dummy.matrix);for(let l=0;l<7;l++){dummy.position.set(p.x,p.h+3,p.z);dummy.rotation.set(0,l/7*Math.PI*2,0);dummy.scale.setScalar(.75+rand()*.35);dummy.updateMatrix();palmLeaves.setMatrixAt(i*7+l,dummy.matrix)}});scene.add(trunks,palmLeaves);
 const boats=[];for(let i=0;i<5;i++){const boat=new THREE.Group();const hull=new THREE.Mesh(new THREE.BoxGeometry(10,3,26),new THREE.MeshStandardMaterial({color:0x5b3922}));hull.position.y=1;boat.add(hull);const roof=new THREE.Mesh(new THREE.CapsuleGeometry(4,15,4,8),new THREE.MeshStandardMaterial({color:0xb59959}));roof.rotation.x=Math.PI/2;roof.position.y=5;boat.add(roof);boat.position.set(-220+i*130,0,-1980-i*110);boat.rotation.y=.3+i*.3;scene.add(boat);boats.push(boat)}
 const states=[{pos:[420,310,610],look:[-15,50,0]},{pos:[-370,330,490],look:[-100,65,-160]},{pos:[430,300,-1650],look:[30,0,-2250]},{pos:[-540,240,-2820],look:[-110,0,-2350]}];let target=new THREE.Vector3(...states[0].look),desired=new THREE.Vector3(...states[0].pos),look=target.clone();camera.position.copy(desired);let chapter=0,drag=false,previous={x:0,y:0},auto=false,autoTime=0,zoom=1;const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;let last=0;
 const markerSets=[[['munnar','Munnar · Tea country',-40,130],['eravikulam','Eravikulam',-140,-110],['mattupetty','Mattupetty Lake',210,-30]],[['chembra','Chembra Peak',-170,80],['edakkal','Edakkal Caves',-290,-100],['silent-valley','Silent Valley',50,-160]],[['alleppey','Alappuzha',0,-2030],['kumarakom','Kumarakom',180,-2260],['munroe','Munroe Island',-150,-2240]],[['varkala','Varkala',-300,-2450],['kochi','Fort Kochi',-130,-2250],['bekal','Bekal',130,-2520]]];let markers=[];function makeMarkers(){document.querySelector('#pins').replaceChildren();markers=markerSets[chapter].map(([id,label,x,z])=>{const el=document.createElement('button');el.className='pin';el.textContent=label;el.setAttribute('aria-label','Explore '+label);el.onclick=()=>onPin(id);document.querySelector('#pins').append(el);return{el,p:new THREE.Vector3(x,chapter<2?height(x,z)+12:20,z)}})}makeMarkers();
 canvas.addEventListener('pointerdown',e=>{drag=true;previous={x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-previous.x,dy=e.clientY-previous.y;desired.x-=dx*.85;desired.z+=dy*.7;previous={x:e.clientX,y:e.clientY};auto=false});const release=()=>drag=false;canvas.addEventListener('pointerup',release);canvas.addEventListener('pointercancel',release);canvas.addEventListener('wheel',e=>{e.preventDefault();setZoom(e.deltaY>0?1.08:.92)},{passive:false});function setZoom(v){zoom=THREE.MathUtils.clamp(zoom*v,.55,1.65);const st=states[chapter];desired.set(...st.pos).sub(target).multiplyScalar(zoom).add(target)}
 function setChapter(n){chapter=n;zoom=1;target.set(...states[n].look);desired.set(...states[n].pos);makeMarkers()}
 function resize(){const box=canvas.parentElement.getBoundingClientRect();camera.aspect=box.width/box.height;camera.updateProjectionMatrix();renderer.setSize(box.width,box.height,false)}window.addEventListener('resize',resize);resize();
 function frame(t){requestAnimationFrame(frame);if(document.hidden)return;const dt=Math.min((t-last)/1000,.05);last=t;if(auto&&!reduce){autoTime+=dt;desired.x+=Math.sin(autoTime*.16)*dt*6;desired.z-=dt*2}camera.position.lerp(desired,reduce?1:.035);look.lerp(target,reduce?1:.04);camera.lookAt(look);clouds.forEach((c,i)=>{if(!reduce)c.position.x+=dt*(1+i*.04)});for(const m of markers){const p=m.p.clone().project(camera);const w=canvas.clientWidth,h=canvas.clientHeight,x=(p.x*.5+.5)*w,y=(-p.y*.5+.5)*h;const visible=p.z<1&&x>w*.35&&x<w*.91&&y>h*(w<700?.62:.30)&&y<h*.72;m.el.style.left=x+'px';m.el.style.top=y+'px';m.el.style.display=visible?'flex':'none'}renderer.render(scene,camera)}requestAnimationFrame(frame);onSceneReady?.();return{setChapter,zoom:setZoom,reset(){setChapter(chapter)},flight(v){auto=v},setSun(){}};
}
